# Generated by Django 5.1.2 on 2025-07-24 20:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0006_policy_cover_amount"),
        ("schemes", "0004_schemegroup"),
        ("users", "0003_alter_membershipstatusupdate_next_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creditor_name", models.CharField(max_length=255)),
                ("contact_person_name", models.CharField(max_length=255, null=True)),
                ("contact_person_email", models.EmailField(max_length=254, null=True)),
                (
                    "contact_person_phone_number",
                    models.CharField(max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=255, null=True)),
                ("town", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("date_registered", models.DateField(null=True)),
                ("loan_reference", models.CharField(max_length=255, null=True)),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("term_months", models.IntegerField(default=1)),
                ("declining_term", models.BooleanField(default=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membershipcreditors",
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policycreditors",
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schemegroupcreditors",
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
