# Generated by Django 5.1.2 on 2025-07-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("schemes", "0003_alter_scheme_scheme_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="schemes.scheme",
            ),
        ),
    ]
