# Generated by Django 5.1.2 on 2025-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_scheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="policy_number_prefix",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
