# Generated by Django 5.1.7 on 2026-01-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuredGadget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
