# Generated by Django 5.1.7 on 2026-01-18 17:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="insuredgadget",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="device_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="device_model",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="device_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="imei_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="purchase_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="serial_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="DeviceOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[("Seller", "Seller"), ("Repair", "Repair")],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=255)),
                ("website", models.URLField(null=True)),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(default="Kenya", max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gadgets.deviceoutlet",
            ),
        ),
    ]
