# Generated by Django 5.1.7 on 2026-01-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gadgets",
            "0002_insuredgadget_description_insuredgadget_device_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceoutlet",
            name="outlet_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="insuredgadget",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insuredgadget",
            name="device_model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="insuredgadget",
            name="device_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="insuredgadget",
            name="purchase_date",
            field=models.DateField(),
        ),
    ]
