# Generated by Django 5.1.7 on 2026-01-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0003_deviceoutlet_outlet_number_and_more"),
        ("pricing", "0009_gadgetpricingcomponent_included_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuredgadget",
            name="pricing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.gadgetpricing",
            ),
        ),
    ]
