# Generated by Django 5.1.7 on 2026-01-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0004_insuredgadget_pricing"),
        ("pricing", "0009_gadgetpricingcomponent_included_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredgadget",
            name="pricing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pricing.gadgetpricing"
            ),
        ),
    ]
