# Generated by Django 5.1.7 on 2026-01-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0006_insuredgadget_policy"),
        ("policies", "0006_policy_cover_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredgadget",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="policies.policy"
            ),
        ),
    ]
