# Generated by Django 5.1.7 on 2026-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0007_alter_insuredgadget_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuredgadget",
            name="device_brand",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
