# Generated by Django 5.1.7 on 2026-01-19 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0008_insuredgadget_device_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuredgadget",
            name="insurer_share",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="platform_share",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="seller_share",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
