# Generated by Django 5.1.7 on 2026-01-19 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0009_insuredgadget_insurer_share_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuredgadget",
            name="premium",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
