# Generated by Django 5.1.7 on 2026-01-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0010_insuredgadget_premium"),
        ("policies", "0006_policy_cover_amount"),
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredgadget",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membershipgadgets",
                to="users.membership",
            ),
        ),
        migrations.AlterField(
            model_name="insuredgadget",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policygadgets",
                to="policies.policy",
            ),
        ),
    ]
