# Generated by Django 5.1.7 on 2026-01-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0011_alter_insuredgadget_membership_and_more"),
        ("policies", "0007_alter_policystatusupdate_policy"),
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredgadget",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_gadgets",
                to="users.membership",
            ),
        ),
        migrations.AlterField(
            model_name="insuredgadget",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_gadgets",
                to="policies.policy",
            ),
        ),
    ]
