# Generated by Django 5.1.7 on 2026-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0012_alter_insuredgadget_membership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuredgadget",
            name="warranty_expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="insuredgadget",
            name="warranty_period",
            field=models.IntegerField(help_text="Warranty period in months", null=True),
        ),
    ]
