# Generated by Django 5.1.7 on 2026-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadgets", "0014_deviceoutlet_business_registration_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceoutlet",
            name="business_registration_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deviceoutlet",
            name="tax_identification_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
