# Generated by Django 5.1.2 on 2025-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_title", models.CharField(max_length=255)),
                ("action_type", models.CharField(max_length=255)),
                ("action_description", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
