# Generated by Django 5.1.2 on 2025-07-18 19:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_product_scheme"),
        ("schemes", "0003_alter_scheme_scheme_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schemes.scheme"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MainMemberPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_level",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[
                            ("Spouse", "Spouse"),
                            ("Child", "Child"),
                            ("Son", "Son"),
                            ("Daughter", "Daughter"),
                        ],
                        max_length=255,
                    ),
                ),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DependentPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_level",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
