# Generated by Django 5.1.2 on 2025-07-18 19:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainmemberpricing",
            name="dependent_type",
        ),
        migrations.AddField(
            model_name="dependentpricing",
            name="dependent_type",
            field=models.CharField(
                choices=[
                    ("Spouse", "Spouse"),
                    ("Child", "Child"),
                    ("Son", "Son"),
                    ("Daughter", "Daughter"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ExtendedDependentPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_level",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
