# Generated by Django 5.1.2 on 2025-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_remove_mainmemberpricing_dependent_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependentpricing",
            name="dependent_type",
            field=models.CharField(
                choices=[
                    ("Spouse", "Spouse"),
                    ("Child", "Child"),
                    ("Son", "Son"),
                    ("Daughter", "Daughter"),
                ],
                max_length=255,
            ),
        ),
    ]
