# Generated by Django 5.1.2 on 2025-07-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_alter_dependentpricing_dependent_type"),
        ("products", "0002_alter_product_scheme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dependentpricing",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="extendeddependentpricing",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="mainmemberpricing",
            name="plan",
        ),
        migrations.AddField(
            model_name="dependentpricing",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="extendeddependentpricing",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="mainmemberpricing",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.DeleteModel(
            name="PricingPlan",
        ),
    ]
