# Generated by Django 5.1.2 on 2025-07-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0005_alter_dependentpricing_product_and_more"),
        ("products", "0002_alter_product_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependentpricing",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependentprices",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="extendeddependentpricing",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extendeddependentprices",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="mainmemberpricing",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mainmemberprices",
                to="products.product",
            ),
        ),
    ]
