# Generated by Django 5.1.2 on 2025-07-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0006_alter_dependentpricing_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainmemberpricing",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
