# Generated by Django 5.1.7 on 2026-01-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0007_mainmemberpricing_name"),
        ("products", "0003_product_policy_number_prefix"),
    ]

    operations = [
        migrations.CreateModel(
            name="GadgetPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_type",
                    models.CharField(
                        choices=[
                            ("Full Cover", "Full Cover"),
                            ("Partial Cover", "Partial Cover"),
                        ],
                        default="Partial Cover",
                        max_length=255,
                    ),
                ),
                ("cover_percentage", models.FloatField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GadgetPricingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.gadgetpricing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
