# Generated by Django 5.1.7 on 2026-01-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0008_gadgetpricing_gadgetpricingcomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="gadgetpricingcomponent",
            name="included",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="gadgetpricingcomponent",
            name="pricing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricingcomponents",
                to="pricing.gadgetpricing",
            ),
        ),
    ]
