# Generated by Django 5.1.7 on 2026-03-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0010_policy_gadget_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "notification_category",
                    models.CharField(
                        choices=[
                            ("Premium Paid", "Premium Paid"),
                            ("Policy Cancelled", "Policy Cancelled"),
                            ("Policy Expiring Soon", "Policy Expiring Soon"),
                            ("New Policy", "New Policy"),
                            ("Claim Approved", "Claim Approved"),
                            ("Claim Rejected", "Claim Rejected"),
                            ("Payment Reminder", "Payment Reminder"),
                            ("Policy Lapsed", "Policy Lapsed"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "notification_channel",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Push Notification", "Push Notification"),
                            ("All Channels", "All Channels"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Sent", "Sent"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                            ("Read", "Read"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_storage",
                        to="policies.policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_storage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Sent", "Sent"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                            ("Read", "Read"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="notifications.notificationstorage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
