# Generated by Django 5.1.2 on 2025-07-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_membershipstatusupdate_next_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="county",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ward",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
