# Generated by Django 5.1.7 on 2026-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="preferred_communication_channel",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Created", "Created"),
                    ("Active", "Active"),
                    ("Cancelled", "Cancelled"),
                    ("Lapsed", "Lapsed"),
                    ("Deactivated", "Deactivated"),
                ],
                default="Created",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Policy Owner", "Policy Owner"),
                    ("Sales Agent", "Sales Agent"),
                    ("Broker", "Broker"),
                    ("Admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
