# Generated by Django 5.1.7 on 2026-03-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0012_policy_payment_method"),
        ("users", "0005_membership_preferred_communication_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policymemberships",
                to="policies.policy",
            ),
        ),
    ]
