# Generated by Django 5.1.7 on 2026-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_activation_token_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
