# Generated by Django 5.1.7 on 2026-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(default="Pending Verification", max_length=255),
        ),
    ]
