# Generated by Django 5.1.2 on 2025-07-20 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_number", models.CharField(max_length=255)),
                ("start_date", models.DateField(null=True)),
                ("maturity_date", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Lapsed", "Lapsed"),
                            ("Deactivated", "Deactivated"),
                        ],
                        default="Created",
                        max_length=255,
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Lapsed", "Lapsed"),
                            ("Deactivated", "Deactivated"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "next_status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Lapsed", "Lapsed"),
                            ("Deactivated", "Deactivated"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policystatusupdates",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
