# Generated by Django 5.1.2 on 2025-07-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_policy_product"),
        ("products", "0003_product_policy_number_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="products.product",
            ),
        ),
    ]
