# Generated by Django 5.1.2 on 2025-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_alter_policy_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policystatusupdate",
            name="next_status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Created", "Created"),
                    ("Active", "Active"),
                    ("Cancelled", "Cancelled"),
                    ("Lapsed", "Lapsed"),
                    ("Deactivated", "Deactivated"),
                ],
                default="Created",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="policystatusupdate",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Created", "Created"),
                    ("Active", "Active"),
                    ("Cancelled", "Cancelled"),
                    ("Lapsed", "Lapsed"),
                    ("Deactivated", "Deactivated"),
                ],
                default="Draft",
                max_length=255,
            ),
        ),
    ]
