# Generated by Django 5.1.2 on 2025-07-23 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0005_alter_policystatusupdate_next_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="cover_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
    ]
