# Generated by Django 5.1.7 on 2026-01-19 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0006_policy_cover_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policystatusupdate",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_status_updates",
                to="policies.policy",
            ),
        ),
    ]
