# Generated by Django 5.1.7 on 2026-01-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0007_alter_policystatusupdate_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="policy_document",
            field=models.FileField(null=True, upload_to="policy_documents/"),
        ),
    ]
