# Generated by Django 5.1.7 on 2026-01-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0009_policy_policy_owner"),
        ("pricing", "0009_gadgetpricingcomponent_included_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="gadget_pricing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.gadgetpricing",
            ),
        ),
    ]
