# Generated by Django 5.1.7 on 2026-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0010_policy_gadget_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="purchase_channel",
            field=models.CharField(default="Direct", max_length=255),
        ),
    ]
