# Generated by Django 5.1.7 on 2026-03-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0011_policy_purchase_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="payment_method",
            field=models.CharField(default="Mpesa", max_length=255),
        ),
    ]
