# Generated by Django 5.1.7 on 2026-03-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0012_policy_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="preferred_communication_channel",
            field=models.CharField(default="Email", max_length=255),
        ),
    ]
