# Generated by Django 5.1.2 on 2025-07-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("users", "0003_alter_membershipstatusupdate_next_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_name", models.CharField(max_length=255, null=True)),
                ("account_type", models.CharField(max_length=255, null=True)),
                ("account_name", models.CharField(max_length=255, null=True)),
                ("account_number", models.CharField(max_length=255, null=True)),
                ("branch_code", models.CharField(max_length=255, null=True)),
                ("debit_order_date", models.CharField(max_length=255, null=True)),
                ("source_of_funds", models.CharField(max_length=255, null=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paymentdetails",
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
