# Generated by Django 5.1.2 on 2025-07-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payerdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premium",
            name="status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Failed", "Failed"), ("Future", "Future")],
                default="Future",
                max_length=255,
            ),
        ),
    ]
