# Generated by Django 5.1.2 on 2025-07-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_premium_status"),
        ("policies", "0006_policy_cover_amount"),
        ("schemes", "0004_schemegroup"),
        ("users", "0003_alter_membershipstatusupdate_next_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payerdetail",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="payerdetail",
            name="scheme_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.schemegroup",
            ),
        ),
        migrations.AlterField(
            model_name="payerdetail",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paymentdetails",
                to="users.membership",
            ),
        ),
    ]
