# Generated by Django 5.1.2 on 2025-07-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payerdetail_policy_payerdetail_scheme_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payerdetail",
            name="payment_method",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
