# Generated by Django 5.1.7 on 2026-01-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payerdetail_payment_method"),
        ("policies", "0008_policy_policy_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payerdetail",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payer_details",
                to="policies.policy",
            ),
        ),
    ]
