# Generated by Django 5.1.7 on 2026-01-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payerdetail_policy"),
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.RenameField(
            model_name="premium",
            old_name="expected_date",
            new_name="due_date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="policy",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="scheme_group",
        ),
        migrations.RemoveField(
            model_name="premium",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="premium",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="premium",
            name="reference",
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("Future", "Future"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.membership"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="premium",
            name="expected_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="premium",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.membership"
            ),
        ),
        migrations.AlterField(
            model_name="premium",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("Future", "Future"),
                    ("Pending", "Pending"),
                ],
                default="Future",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PremiumPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="payments.payment",
                    ),
                ),
                (
                    "premium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="payments.premium",
                    ),
                ),
            ],
            options={
                "unique_together": {("premium", "payment")},
            },
        ),
    ]
