# Generated by Django 5.1.7 on 2026-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_rename_expected_date_premium_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payerdetail",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
