# Generated by Django 5.1.2 on 2025-07-20 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        ("schemes", "0004_schemegroup"),
        ("users", "0002_membership_membershipstatusupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Spouse", "Spouse"),
                            ("Child", "Child"),
                            ("Son", "Son"),
                            ("Daughter", "Daughter"),
                            ("Parent", "Parent"),
                            ("Grand Parent", "Grand Parent"),
                            ("Niece", "Niece"),
                            ("Nephew", "Nephew"),
                            ("Aunt", "Aunt"),
                            ("Uncle", "Uncle"),
                            ("In Law", "In Law"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Lapsed", "Lapsed"),
                            ("Deactivated", "Deactivated"),
                        ],
                        default="Active",
                        max_length=255,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Spouse", "Spouse"),
                            ("Child", "Child"),
                            ("Son", "Son"),
                            ("Daughter", "Daughter"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "cover_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Lapsed", "Lapsed"),
                            ("Deactivated", "Deactivated"),
                        ],
                        default="Active",
                        max_length=255,
                    ),
                ),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[("Dependent", "Dependent"), ("Extended", "Extended")],
                        max_length=255,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
