# Generated by Django 5.1.2 on 2025-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="passport_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dependent",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dependent",
            name="passport_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
