# Generated by Django 5.1.2 on 2025-07-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_beneficiary_id_number_beneficiary_passport_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Created", "Created"),
                    ("Active", "Active"),
                    ("Cancelled", "Cancelled"),
                    ("Lapsed", "Lapsed"),
                    ("Deactivated", "Deactivated"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Created", "Created"),
                    ("Active", "Active"),
                    ("Cancelled", "Cancelled"),
                    ("Lapsed", "Lapsed"),
                    ("Deactivated", "Deactivated"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
    ]
