# Generated by Django 5.1.2 on 2025-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0003_alter_beneficiary_status_alter_dependent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependent",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("Spouse", "Spouse"),
                    ("Child", "Child"),
                    ("Son", "Son"),
                    ("Daughter", "Daughter"),
                    ("Parent", "Parent"),
                    ("Grand Parent", "Grand Parent"),
                    ("Niece", "Niece"),
                    ("Nephew", "Nephew"),
                    ("Aunt", "Aunt"),
                    ("Uncle", "Uncle"),
                    ("In Law", "In Law"),
                ],
                max_length=255,
            ),
        ),
    ]
