# Generated by Django 5.1.2 on 2025-07-26 18:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0004_alter_dependent_relationship"),
        ("policies", "0006_policy_cover_amount"),
        ("schemes", "0004_schemegroup"),
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_type", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("imei_number", models.CharField(max_length=255, null=True)),
                ("serial_number", models.CharField(max_length=255, null=True)),
                ("warranty_end_date", models.DateField(null=True)),
                (
                    "cover_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InsuredPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("pet_type", models.CharField(max_length=255)),
                ("breed", models.CharField(max_length=255, null=True)),
                ("gender", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("microchip_number", models.CharField(max_length=255, null=True)),
                ("cover_type", models.CharField(max_length=255, null=True)),
                ("neutered", models.BooleanField(default=True)),
                ("vaccinated", models.BooleanField(default=True)),
                (
                    "cover_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InsuredVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registration_number", models.CharField(max_length=255)),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year_of_manufacture", models.IntegerField()),
                ("engine_number", models.CharField(max_length=255, null=True)),
                ("chasis", models.CharField(max_length=255, null=True)),
                ("usage_type", models.CharField(max_length=255, null=True)),
                ("color", models.CharField(max_length=255, null=True)),
                (
                    "vehicle_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("cover_type", models.CharField(max_length=255, null=True)),
                ("windscreen_covered", models.BooleanField(default=True)),
                ("political_violence_covered", models.BooleanField(default=True)),
                ("excess_protector", models.BooleanField(default=True)),
                (
                    "cover_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
