# Generated by Django 5.1.2 on 2025-07-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0006_policy_cover_amount"),
        ("schemes", "0004_schemegroup"),
        ("users", "0004_user_county_user_occupation_user_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuredBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("industry", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=10,
                    ),
                ),
                ("annual_revenue", models.BigIntegerField()),
                ("employee_count", models.PositiveIntegerField()),
                ("has_security_measures", models.BooleanField(default=False)),
                ("has_incident_response_plan", models.BooleanField(default=False)),
                ("cover_limit", models.BigIntegerField()),
                ("premium", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cover_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("comprehensive", "Comprehensive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("property_cover", models.BigIntegerField()),
                ("public_liability_cover", models.BigIntegerField()),
                ("employer_liability_cover", models.BigIntegerField()),
                ("interruption_cover", models.BigIntegerField()),
                ("theft_cover", models.BooleanField(default=False)),
                ("money_in_transit", models.BooleanField(default=False)),
                ("electronic_equipment_cover", models.BigIntegerField()),
                (
                    "premises_type",
                    models.CharField(
                        choices=[("owned", "Owned"), ("rented", "Rented")],
                        max_length=20,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
