# Generated by Django 5.1.2 on 2025-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="scheme_type",
            field=models.CharField(
                choices=[
                    ("GROUP_SCHEME", "Group"),
                    ("INDIVIDUAL_SCHEME", "Individual"),
                ],
                max_length=255,
            ),
        ),
    ]
