# Generated by Django 5.1.2 on 2025-07-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0002_alter_scheme_scheme_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="scheme_type",
            field=models.CharField(
                choices=[("Group", "Group"), ("Individual", "Individual")],
                max_length=255,
            ),
        ),
    ]
